import fs from 'node:fs/promises';
import path from 'node:path';
import express, { type Request, type Response, type NextFunction } from 'express';
import helmet from 'helmet';

// Constants
const port = process.env.PORT || 3551;
const root = process.cwd();
const isProd = process.env.NODE_ENV === 'production';

// Cached production assets
const templateHtml = await fs.readFile('./dist/client/index.html', 'utf8').catch(() => '');

async function createServer() {
	const app = express();

	// Security: remove X-Powered-By and add protective HTTP headers
	app.use(helmet({
		contentSecurityPolicy: {
			directives: {
				defaultSrc: ["'self'"],
				scriptSrc: ["'self'", "'unsafe-inline'"],
				styleSrc: ["'self'", "'unsafe-inline'"],
				imgSrc: ["'self'", 'data:'],
				connectSrc: ["'self'"],
				fontSrc: ["'self'"],
				objectSrc: ["'none'"],
				frameAncestors: ["'none'"],
			},
		},
	}));

	// Security: limit request body size to prevent payload-based DoS
	app.use(express.json({ limit: '10kb' }));
	app.use(express.urlencoded({ extended: false, limit: '10kb' }));

	const compression = await import('compression');
	app.use(compression.default());
	// Serve static assets generated by Vite (JS/CSS/fonts/images). Do not serve index.html.
	app.use('/assets', express.static(resolve('dist/client/assets')));

	// Serve HTML via SSR for all other routes
	app.all('*', async (request: Request, res: Response) => {
		try {
			const url = request.originalUrl;

			const template = templateHtml;
			// @ts-ignore
			const { render } = await import(root + '/dist/server/entry-server.js');

			const rendered = await render(url);

			const appHtml = typeof rendered === 'string' ? rendered : (rendered.html ?? '');
			const status = typeof rendered === 'object' && rendered !== null ? (rendered.status ?? 200) : 200;

			const html = template.replace('<!-- SSR OUTLET -->', appHtml);

			res.status(status).set({ 'Content-Type': 'text/html' }).send(html);
		} catch (error: any) {
			// Security: never expose stack traces to the client
			console.error(error.stack);
			res.status(500).end(isProd ? 'Internal Server Error' : error.stack);
		}
	});

	process.on('uncaughtException', error => {
		console.error(error);
		process.exit(1);
	});

	// Error handling middleware
	app.use((error: any, request: Request, res: Response, _next: NextFunction) => {
		// Security: never expose stack traces to the client
		console.error(error.stack);
		res.status(500).end(isProd ? 'Internal Server Error' : error.stack);
	});

	return app;
}

// Start http server
createServer().then(app => {
	app.listen(port, () => {
		console.log(`HTTP server is running at http://localhost:${port}`);
	});
}).catch(error => {
	console.error(error);
	process.exit(1);
});

function resolve(p: string) {
	return path.resolve(root, p);
}
